//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fees()
        {
            this.fees_details = new HashSet<fees_details>();
        }
    
        public int fees_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> month_id { get; set; }
    
        public virtual admin admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fees_details> fees_details { get; set; }
        public virtual month_of_fees month_of_fees { get; set; }
        public virtual student student { get; set; }
    }
}
