//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fees_details
    {
        public int fees_detail_id { get; set; }
        public Nullable<int> fees_id { get; set; }
        public Nullable<int> registration_id { get; set; }
        public Nullable<bool> paid { get; set; }
    
        public virtual fees fees { get; set; }
        public virtual registration registration { get; set; }
    }
}
