//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tutorsystemEntities1 : DbContext
    {
        public tutorsystemEntities1()
            : base("name=tutorsystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<complaint> complaints { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<fees_details> fees_details { get; set; }
        public virtual DbSet<fees> feeses { get; set; }
        public virtual DbSet<month_of_fees> month_of_fees { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<teacher_courses> teacher_courses { get; set; }
        public virtual DbSet<teacher_salaries> teacher_salaries { get; set; }
        public virtual DbSet<teacher_salary_details> teacher_salary_details { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<vw_attendance> vw_attendance { get; set; }
        public virtual DbSet<vw_complaints> vw_complaints { get; set; }
        public virtual DbSet<vw_ex> vw_ex { get; set; }
        public virtual DbSet<vw_fees> vw_fees { get; set; }
        public virtual DbSet<vw_month> vw_month { get; set; }
        public virtual DbSet<vw_monthbhosri> vw_monthbhosri { get; set; }
        public virtual DbSet<vw_students> vw_students { get; set; }
        public virtual DbSet<vw_teacher_salaries> vw_teacher_salaries { get; set; }
        public virtual DbSet<vw_teachers> vw_teachers { get; set; }
        public virtual DbSet<vw_registrations> vw_registrations { get; set; }
        public virtual DbSet<vw_fees_details> vw_fees_details { get; set; }
        public virtual DbSet<vw_teacher_courses> vw_teacher_courses { get; set; }
    }
}
