//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher_salaries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teacher_salaries()
        {
            this.teacher_salary_details = new HashSet<teacher_salary_details>();
        }
    
        public int teacher_salary_id { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> month_id { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual month_of_fees month_of_fees { get; set; }
        public virtual teacher teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teacher_salary_details> teacher_salary_details { get; set; }
    }
}
