//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher_courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teacher_courses()
        {
            this.teacher_salary_details = new HashSet<teacher_salary_details>();
        }
    
        public int teacher_course_id { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<System.DateTime> doj { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual teacher teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teacher_salary_details> teacher_salary_details { get; set; }
    }
}
