//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_attendance
    {
        public string student_name { get; set; }
        public string course_name { get; set; }
        public Nullable<bool> attendance { get; set; }
        public Nullable<System.DateTime> attendance_time { get; set; }
    }
}
