//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_fees
    {
        public int fees_id { get; set; }
        public string Student_Name { get; set; }
        public string Admin_Name { get; set; }
        public string Month_Name { get; set; }
        public Nullable<int> amount { get; set; }
    }
}
