//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_registrations
    {
        public string Student_Name { get; set; }
        public string Course_Name { get; set; }
        public Nullable<System.DateTime> Date_Of_joining { get; set; }
    }
}
