//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_teacher_salaries
    {
        public int teacher_id { get; set; }
        public string teacher_name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string month_name { get; set; }
        public Nullable<int> paid_ { get; set; }
    }
}
